"""Hand-written evaluation complaints (not produced by the template generator).

DEV   - 99 complaints that were known while the training templates were expanded.
        Many templates paraphrase them, so the DEV score is optimistic.
FINAL - 66 complaints written only after the templates and model settings were
        frozen. Nothing was changed after scoring them. This is the number to quote.
"""

DEV = [
    ("We get water only for ten minutes in the morning and then nothing the whole day", "Water Supply"),
    ("The overhead tank connection to our chawl was cut and nobody has restored it", "Water Supply"),
    ("Nal se ganda paani aa raha hai, peene layak nahi hai", "Water Supply"),
    ("My scooter tyre burst because of the broken stretch outside the mall", "Roads & Potholes"),
    ("After the cable company dug up the lane they never filled it back properly", "Roads & Potholes"),
    ("Raste mein itne khadde hain ki auto wale aane se mana karte hain", "Roads & Potholes"),
    ("Lights keep going off every hour in our area since last night", "Electricity"),
    ("The junction box outside my shop is open and wires are exposed to rain", "Electricity"),
    ("Light chali gayi hai subah se, abhi tak nahi aayi", "Electricity"),
    ("The bin at the corner of our lane is spilling over and cows are eating plastic", "Garbage & Sanitation"),
    ("Nobody has come to collect household waste from our building this week", "Garbage & Sanitation"),
    ("Kachra uthane wala teen din se nahi aaya", "Garbage & Sanitation"),
    ("Toilet waste is backing up into our bathroom whenever it rains", "Drainage & Sewage"),
    ("The nala behind our houses is choked with plastic and water is entering homes", "Drainage & Sewage"),
    ("Gutter ka paani sadak par beh raha hai aur badbu aa rahi hai", "Drainage & Sewage"),
    ("None of the lamp posts on the bridge are lit after sunset", "Street Lights"),
    ("The bulb on the pole outside house number 12 keeps blinking all night", "Street Lights"),
    ("Raat ko gali mein andhera rehta hai, khamba ki light kharab hai", "Street Lights"),
    ("Three families in our lane have typhoid and we suspect the water stall", "Public Health"),
    ("Packs of stray dogs are biting people near the market", "Public Health"),
    ("The government clinic has run out of medicines and the nurse is absent", "Public Health"),
    ("The 7 am bus never comes on time and students miss their classes", "Public Transport"),
    ("Conductor refused to give me a ticket and kept the change", "Public Transport"),
    ("There is no seating or roof at the bus stand and people wait in the sun", "Public Transport"),
    ("A tea stall owner has built a permanent room on the pavement", "Encroachment"),
    ("Cars from the showroom are parked on the public road all day blocking it", "Encroachment"),
    ("Someone has put up a wall across the common passage used by residents", "Encroachment"),
    ("A group of men gamble and drink outside the school gate every evening", "Safety & Law"),
    ("My mobile phone was snatched by two men on a bike near the signal", "Safety & Law"),
    ("Women are being followed on the walking track after dark", "Safety & Law"),
    ("A heavy branch is hanging over the footpath and could fall on someone", "Tree & Parks"),
    ("The municipal garden is full of weeds and the benches are broken", "Tree & Parks"),
    ("Someone chopped down two old banyan trees at night without permission", "Tree & Parks"),
    # second batch, written before the template expansion but seen during it
    ("The corporation tap in our gully has been dry since the weekend", "Water Supply"),
    ("Water from the pipeline is brownish and has worms in it", "Water Supply"),
    ("A pipe has cracked under the road and clean water is gushing out for hours", "Water Supply"),
    ("Our society has not received the tanker we booked and paid for", "Water Supply"),
    ("Paani ka pressure bahut kam hai, upar ki manzil tak nahi chadhta", "Water Supply"),
    ("Subah se nal mein paani nahi aaya, bachche school kaise jayenge", "Water Supply"),
    ("There is a massive ditch right in the middle of the flyover approach", "Roads & Potholes"),
    ("The newly laid asphalt has peeled off within a month", "Roads & Potholes"),
    ("Loose stones are scattered all over the lane after the repair work and bikes are slipping", "Roads & Potholes"),
    ("The divider is broken and iron rods are sticking out on the main road", "Roads & Potholes"),
    ("Road ki halat bahut kharab hai, gaadi chalana mushkil ho gaya hai", "Roads & Potholes"),
    ("Barsaat ke baad poori sadak toot gayi hai", "Roads & Potholes"),
    ("We have had a blackout in our colony since the storm last evening", "Electricity"),
    ("The fuse in the distribution box keeps tripping and half the building has no current", "Electricity"),
    ("My electricity bill is three times the usual amount and the meter reading is wrong", "Electricity"),
    ("A cable snapped and is lying on the wet ground giving shocks to passers-by", "Electricity"),
    ("Current nahi hai kal raat se, fridge ka saara saaman kharab ho gaya", "Electricity"),
    ("Transformer se chingari nikal rahi hai, jaldi kisi ko bhejo", "Electricity"),
    ("Trash has been piling up behind the apartment block and it smells horrible", "Garbage & Sanitation"),
    ("The ghanta gadi has stopped coming to our street", "Garbage & Sanitation"),
    ("Someone dumped a truckload of rubble and old furniture on the empty plot", "Garbage & Sanitation"),
    ("The community toilet has no water and has not been cleaned in weeks", "Garbage & Sanitation"),
    ("Kooda sadak par pada hai aur koi saaf nahi kar raha", "Garbage & Sanitation"),
    ("Gali mein jhadu lagane wala kai dino se nahi aaya", "Garbage & Sanitation"),
    ("Dirty water from the sewer is coming up through the manhole onto the street", "Drainage & Sewage"),
    ("Our lane floods knee-deep every time it rains because the drain is clogged", "Drainage & Sewage"),
    ("The cover of the sewer chamber is cracked and a child almost fell in", "Drainage & Sewage"),
    ("The septic line is leaking into the neighbouring compound", "Drainage & Sewage"),
    ("Naali jaam ho gayi hai aur ganda paani ghar ke andar aa raha hai", "Drainage & Sewage"),
    ("Sewer line toot gayi hai, poore mohalle mein badbu hai", "Drainage & Sewage"),
    ("The lights along the service road have been out for a fortnight", "Street Lights"),
    ("A lamp post near the crossing has been knocked down by a truck", "Street Lights"),
    ("The high mast light at the junction does not switch on at night", "Street Lights"),
    ("Street lamps in our lane stay lit all day long", "Street Lights"),
    ("Hamari gali ki street light kai hafte se band hai", "Street Lights"),
    ("Khambe par bulb nahi hai, raat ko kuch dikhta nahi", "Street Lights"),
    ("Several children in our building have chickenpox and nobody from the health office has visited", "Public Health"),
    ("A sweet shop is selling stale food and many customers got stomach infection", "Public Health"),
    ("There are swarms of mosquitoes in the evening and my neighbour has malaria", "Public Health"),
    ("The vaccination centre turned us away saying there is no stock", "Public Health"),
    ("Mohalle mein bahut log bimar hain, bukhar aur ulti ho rahi hai", "Public Health"),
    ("Awara kutte ne bachche ko kaat liya, injection nahi mil raha", "Public Health"),
    ("The last bus on our route has been cancelled without any notice", "Public Transport"),
    ("The driver did not halt at the stop even though passengers were waving", "Public Transport"),
    ("The bus was so packed that people were hanging from the door", "Public Transport"),
    ("The ticket machine was not working and the conductor overcharged everyone", "Public Transport"),
    ("Bus bahut der se aati hai, roz office late pahunchte hain", "Public Transport"),
    ("Bus stop par baithne ki jagah nahi hai aur shed toota hua hai", "Public Transport"),
    ("A garage has taken over half the lane for repairing vehicles", "Encroachment"),
    ("Vegetable carts block the entire sidewalk outside the station every evening", "Encroachment"),
    ("My neighbour has extended his house onto the municipal road", "Encroachment"),
    ("Political banners have been put up illegally on every pole in the chowk", "Encroachment"),
    ("Footpath par dukaan laga di hai, chalne ki jagah nahi bachi", "Encroachment"),
    ("Sarkari zameen par kisi ne kabza kar liya hai", "Encroachment"),
    ("There was a break-in at the shop next door last night", "Safety & Law"),
    ("A gang of youths on bikes are racing and threatening residents every night", "Safety & Law"),
    ("Girls are being teased by men standing outside the coaching centre", "Safety & Law"),
    ("People are openly selling liquor and drugs behind the playground", "Safety & Law"),
    ("Raat ko chori ho gayi, police ko bulao", "Safety & Law"),
    ("Ladke ladkiyon ko pareshan karte hain bus stop par", "Safety & Law"),
    ("An old peepal tree is leaning dangerously towards our house", "Tree & Parks"),
    ("The jogging track in the public garden is broken and overgrown", "Tree & Parks"),
    ("Branches have not been trimmed and they are scraping the roofs of buses", "Tree & Parks"),
    ("The park gate is locked all day and the fountain has not worked for months", "Tree & Parks"),
    ("Ped gir gaya hai raste par, hatane koi nahi aaya", "Tree & Parks"),
    ("Garden mein jhule toote hue hain, bachche khel nahi sakte", "Tree & Parks"),
]

FINAL = [
    ("For the past fortnight the supply has been erratic and we store water in buckets", "Water Supply"),
    ("The borewell motor of the corporation has failed and the whole slum is without water", "Water Supply"),
    ("There is oil floating in the water we get from the municipal line", "Water Supply"),
    ("A leak near the meter is wasting water day and night and nobody attends to it", "Water Supply"),
    ("Hamare yahan teen din se paani ki supply band hai", "Water Supply"),
    ("Tanki mein paani nahi chadh raha, motor chalane par bhi nahi aata", "Water Supply"),
    ("The stretch outside the hospital is so uneven that patients in ambulances suffer", "Roads & Potholes"),
    ("A manhole-sized pit has opened up on the carriageway and two cars were damaged", "Roads & Potholes"),
    ("The concrete road has developed wide cracks within a year", "Roads & Potholes"),
    ("Paver blocks on the walkway are loose and an old lady fractured her leg", "Roads & Potholes"),
    ("Pul ke paas road dhans gaya hai", "Roads & Potholes"),
    ("Hamari gali ka road aaj tak nahi bana, barish mein keechad ho jata hai", "Roads & Potholes"),
    ("Supply has been failing every afternoon for a week and the helpline does not answer", "Electricity"),
    ("Sparks fly from the overhead line whenever the wind blows", "Electricity"),
    ("The linesman demanded money to restore our connection", "Electricity"),
    ("Our appliances got damaged due to a sudden surge yesterday", "Electricity"),
    ("Do din se bijli gul hai, mobile bhi charge nahi ho raha", "Electricity"),
    ("Meter tez chal raha hai, har mahine bill double aa raha hai", "Electricity"),
    ("Heaps of refuse outside the school are attracting stray animals", "Garbage & Sanitation"),
    ("The waste collector skips our building unless we tip him", "Garbage & Sanitation"),
    ("Plastic bags and food leftovers are strewn across the playground after the weekly market", "Garbage & Sanitation"),
    ("The public lavatory near the bus depot is filthy and unusable", "Garbage & Sanitation"),
    ("Hafte bhar se kachre ki gaadi nahi aayi, ghar mein kachra jama ho gaya", "Garbage & Sanitation"),
    ("Sadak ki safai kabhi nahi hoti, har taraf gandagi hai", "Garbage & Sanitation"),
    ("Foul water is bubbling out of the gutter in front of the temple", "Drainage & Sewage"),
    ("During yesterday's shower the underpass filled up because the outlets are blocked", "Drainage & Sewage"),
    ("The sewage pipe of our building has burst and the basement is flooded with waste", "Drainage & Sewage"),
    ("An open drain runs along the school wall and children can fall into it", "Drainage & Sewage"),
    ("Gutter ka dhakkan gayab hai, koi gir sakta hai", "Drainage & Sewage"),
    ("Naale ki safai nahi hui, thodi barish mein paani bhar jata hai", "Drainage & Sewage"),
    ("The entire stretch from the temple to the market has no working lamps", "Street Lights"),
    ("One pole light flickers constantly and another is hanging by its wire", "Street Lights"),
    ("We requested a new light for the dark corner months ago and nothing happened", "Street Lights"),
    ("The lights in our lane come on at 10 pm instead of at dusk", "Street Lights"),
    ("Colony ki saari street light kharab padi hain", "Street Lights"),
    ("Pole ki light raat bhar band rehti hai, andhere mein dar lagta hai", "Street Lights"),
    ("Half the students of the municipal school are down with diarrhoea", "Public Health"),
    ("The dispensary opens only twice a week and there is no doctor", "Public Health"),
    ("A pack of dogs attacked a boy and the hospital had no vaccine", "Public Health"),
    ("The butcher throws waste in the open and the shop has no licence or hygiene", "Public Health"),
    ("Ilake mein malaria fail raha hai, dawai ka chhidkav karwaiye", "Public Health"),
    ("Sarkari aspatal mein doctor nahi milte aur dawai bahar se leni padti hai", "Public Health"),
    ("Buses on route 15 run only once an hour although the board says every 15 minutes", "Public Transport"),
    ("The bus sped past the stop and an elderly passenger fell while boarding", "Public Transport"),
    ("The conductor was rude and abused a woman passenger", "Public Transport"),
    ("The shelter at our stop has no roof and the timetable board is missing", "Public Transport"),
    ("Subah ki bus roz late aati hai, bachche school nahi pahunch pate", "Public Transport"),
    ("Driver ne bus stop par gaadi nahi roki", "Public Transport"),
    ("A shopkeeper has permanently covered the footpath with a tin shed", "Encroachment"),
    ("Trucks of a transport company are parked on the public street for weeks", "Encroachment"),
    ("An illegal third storey is being added to the building next door without approval", "Encroachment"),
    ("Hawkers sit right at the hospital gate and ambulances cannot enter", "Encroachment"),
    ("Dukaan walon ne poora footpath gher liya hai", "Encroachment"),
    ("Khali plot par logon ne avaidh kabza kar liya", "Encroachment"),
    ("Thieves broke the lock of the temple donation box last night", "Safety & Law"),
    ("A man on a scooter pulled my gold chain and fled", "Safety & Law"),
    ("Drunk men create a ruckus outside our building every night", "Safety & Law"),
    ("Some boys keep following and whistling at college girls", "Safety & Law"),
    ("Kal raat ghar mein chor ghus gaye aur saaman le gaye", "Safety & Law"),
    ("Kuch log sharab pee kar gali mein jhagda karte hain", "Safety & Law"),
    ("A large neem branch broke off and is blocking the lane", "Tree & Parks"),
    ("The swings and slides in the colony park are rusted and unsafe", "Tree & Parks"),
    ("Trees along the avenue are being felled illegally for a hoarding", "Tree & Parks"),
    ("Nobody waters or maintains the garden and the grass is waist high", "Tree & Parks"),
    ("Aandhi mein ped ukhad gaya, abhi tak pada hai", "Tree & Parks"),
    ("Park mein light nahi hai aur bench tooti padi hain", "Tree & Parks"),
]

# ---------------- Devanagari Hindi / Marathi ----------------
# 33 + 33 complaints (3 per category, the same scenarios in both languages), written
# BEFORE any Devanagari training template existed. Two numbers are reported for them:
#   zero-shot - model trained on English + Hinglish templates only (clean cross-lingual check)
#   final     - after Hindi / Marathi templates were added. Those templates are translations
#               of the existing English ones by the same author, so this is optimistic in the
#               same way DEV is. Real citizen text will score lower.
HI_FINAL = [
    ("हमारी कॉलोनी में पिछले चार दिन से नल में पानी नहीं आ रहा है", "Water Supply"),
    ("नगर निगम के नल से मटमैला और बदबूदार पानी आ रहा है, पीने लायक नहीं है", "Water Supply"),
    ("मुख्य पाइपलाइन फट गई है और हजारों लीटर पानी सड़क पर बह रहा है", "Water Supply"),
    ("स्कूल के सामने वाली सड़क पर बड़े-बड़े गड्ढे हो गए हैं, रोज कोई न कोई गिरता है", "Roads & Potholes"),
    ("केबल डालने के लिए सड़क खोदी गई थी लेकिन उसे वापस ठीक नहीं किया गया", "Roads & Potholes"),
    ("नई बनी सड़क पहली बारिश में ही उखड़ गई", "Roads & Potholes"),
    ("कल रात से हमारे मोहल्ले में बिजली नहीं है", "Electricity"),
    ("ट्रांसफार्मर से चिंगारियां निकल रही हैं और जलने की गंध आ रही है", "Electricity"),
    ("इस महीने बिजली का बिल दोगुना आया है, मीटर खराब लगता है", "Electricity"),
    ("एक हफ्ते से कचरा उठाने वाली गाड़ी नहीं आई है, घर के बाहर कूड़े का ढेर लग गया है", "Garbage & Sanitation"),
    ("सार्वजनिक शौचालय बहुत गंदा है और उसमें पानी भी नहीं है", "Garbage & Sanitation"),
    ("खाली प्लॉट में लोग कूड़ा जला रहे हैं जिससे धुआं फैल रहा है", "Garbage & Sanitation"),
    ("नाली जाम होने से गंदा पानी घरों में घुस रहा है", "Drainage & Sewage"),
    ("सीवर का ढक्कन टूटा हुआ है, कोई भी उसमें गिर सकता है", "Drainage & Sewage"),
    ("थोड़ी सी बारिश में ही पूरी गली में पानी भर जाता है क्योंकि नाले की सफाई नहीं हुई", "Drainage & Sewage"),
    ("हमारी गली की स्ट्रीट लाइट दो हफ्ते से बंद पड़ी है", "Street Lights"),
    ("खंभे की बत्ती दिन भर जलती रहती है और रात को बंद हो जाती है", "Street Lights"),
    ("पुल पर एक भी लाइट नहीं जलती, रात में बहुत अंधेरा रहता है", "Street Lights"),
    ("इलाके में डेंगू के कई मरीज मिले हैं, कृपया फॉगिंग करवाएं", "Public Health"),
    ("आवारा कुत्ते ने एक बच्चे को काट लिया और सरकारी अस्पताल में इंजेक्शन नहीं मिला", "Public Health"),
    ("स्वास्थ्य केंद्र में डॉक्टर नहीं आते और दवाइयां भी खत्म हैं", "Public Health"),
    ("सुबह की बस रोज़ आधा घंटा देर से आती है", "Public Transport"),
    ("कंडक्टर ने टिकट नहीं दिया और ज्यादा पैसे ले लिए", "Public Transport"),
    ("बस स्टॉप पर न छत है न बैठने की जगह", "Public Transport"),
    ("दुकानदारों ने पूरा फुटपाथ घेर लिया है, पैदल चलने की जगह नहीं बची", "Encroachment"),
    ("सरकारी जमीन पर किसी ने अवैध कब्जा करके झोपड़ियां बना ली हैं", "Encroachment"),
    ("पड़ोसी बिना अनुमति के तीसरी मंजिल बना रहा है", "Encroachment"),
    ("कल रात हमारे घर में चोरी हो गई", "Safety & Law"),
    ("कुछ लड़के कॉलेज के बाहर लड़कियों को छेड़ते हैं", "Safety & Law"),
    ("शराब पीकर लोग रोज रात को गली में झगड़ा करते हैं", "Safety & Law"),
    ("आंधी में एक बड़ा पेड़ सड़क पर गिर गया है और रास्ता बंद है", "Tree & Parks"),
    ("पार्क के झूले टूटे हुए हैं, बच्चे खेल नहीं पाते", "Tree & Parks"),
    ("बगीचे में घास बहुत बढ़ गई है और कोई माली नहीं आता", "Tree & Parks"),
]

MR_FINAL = [
    ("आमच्या सोसायटीत गेल्या तीन दिवसांपासून पाणी आलेले नाही", "Water Supply"),
    ("नळाला गढूळ आणि दुर्गंधीयुक्त पाणी येत आहे", "Water Supply"),
    ("मुख्य जलवाहिनी फुटल्यामुळे रस्त्यावर पाणी वाया जात आहे", "Water Supply"),
    ("रस्त्यावर मोठमोठे खड्डे पडले असून दुचाकीस्वार पडत आहेत", "Roads & Potholes"),
    ("केबल टाकण्यासाठी खोदलेला रस्ता अजून दुरुस्त केलेला नाही", "Roads & Potholes"),
    ("नवीन डांबरी रस्ता पहिल्याच पावसात उखडला", "Roads & Potholes"),
    ("काल रात्रीपासून आमच्या भागात वीज नाही", "Electricity"),
    ("ट्रान्सफॉर्मरमधून ठिणग्या उडत आहेत, आग लागण्याची भीती आहे", "Electricity"),
    ("वीज बिल खूप जास्त आले आहे, मीटर चुकीचे रीडिंग दाखवत आहे", "Electricity"),
    ("आठवडाभर कचरा गाडी आलेली नाही, घरासमोर कचऱ्याचा ढीग साचला आहे", "Garbage & Sanitation"),
    ("सार्वजनिक शौचालय अतिशय अस्वच्छ आहे आणि तिथे पाणी नाही", "Garbage & Sanitation"),
    ("मोकळ्या जागेत कचरा जाळला जात आहे, धुरामुळे त्रास होतो", "Garbage & Sanitation"),
    ("गटार तुंबल्यामुळे सांडपाणी घरात शिरत आहे", "Drainage & Sewage"),
    ("ड्रेनेजचे झाकण तुटले आहे, कोणीही आत पडू शकते", "Drainage & Sewage"),
    ("नाल्याची सफाई न झाल्याने थोड्या पावसातही गल्लीत पाणी साचते", "Drainage & Sewage"),
    ("आमच्या गल्लीतील पथदिवे दोन आठवड्यांपासून बंद आहेत", "Street Lights"),
    ("खांबावरील दिवा दिवसभर चालू राहतो आणि रात्री बंद असतो", "Street Lights"),
    ("पुलावर एकही दिवा लागत नाही, रात्री खूप अंधार असतो", "Street Lights"),
    ("आमच्या परिसरात डेंग्यूचे अनेक रुग्ण आढळले आहेत, कृपया धूर फवारणी करा", "Public Health"),
    ("भटक्या कुत्र्याने एका मुलाला चावले आणि सरकारी रुग्णालयात इंजेक्शन मिळाले नाही", "Public Health"),
    ("आरोग्य केंद्रात डॉक्टर येत नाहीत आणि औषधेही संपली आहेत", "Public Health"),
    ("सकाळची बस रोज अर्धा तास उशिरा येते", "Public Transport"),
    ("कंडक्टरने तिकीट दिले नाही आणि जास्त पैसे घेतले", "Public Transport"),
    ("बस थांब्यावर छप्पर नाही आणि बसायला जागा नाही", "Public Transport"),
    ("दुकानदारांनी संपूर्ण पदपथ व्यापला आहे, चालायला जागा नाही", "Encroachment"),
    ("सरकारी जागेवर अनधिकृत झोपड्या उभारल्या आहेत", "Encroachment"),
    ("शेजारी परवानगीशिवाय तिसरा मजला बांधत आहे", "Encroachment"),
    ("काल रात्री आमच्या घरात चोरी झाली", "Safety & Law"),
    ("काही मुले कॉलेजबाहेर मुलींची छेड काढतात", "Safety & Law"),
    ("दारू पिऊन लोक रोज रात्री गल्लीत भांडण करतात", "Safety & Law"),
    ("वादळात मोठे झाड रस्त्यावर पडले असून रस्ता बंद आहे", "Tree & Parks"),
    ("उद्यानातील झोके तुटलेले आहेत, मुले खेळू शकत नाहीत", "Tree & Parks"),
    ("बागेत गवत खूप वाढले आहे आणि माळी येत नाही", "Tree & Parks"),
]

# Probe only: no training template exists in these languages, so this measures pure
# cross-lingual transfer of the embedding model (one complaint per category each).
# Gujarati is in the embedding model's training languages; Bengali and Tamil are not.
_CATS = ["Water Supply", "Roads & Potholes", "Electricity", "Garbage & Sanitation", "Drainage & Sewage", "Street Lights",
         "Public Health", "Public Transport", "Encroachment", "Safety & Law", "Tree & Parks"]
PROBE = {
    "Gujarati": list(zip([
        "અમારા વિસ્તારમાં ત્રણ દિવસથી પાણી આવતું નથી",
        "રસ્તા પર મોટા ખાડા પડી ગયા છે, વાહન ચલાવવું મુશ્કેલ છે",
        "ગઈકાલ રાતથી અમારા વિસ્તારમાં વીજળી નથી",
        "એક અઠવાડિયાથી કચરાની ગાડી આવી નથી, કચરાનો ઢગલો થઈ ગયો છે",
        "ગટર ઉભરાઈ રહી છે અને ગંદુ પાણી ઘરમાં આવે છે",
        "અમારી શેરીની સ્ટ્રીટ લાઇટ બે અઠવાડિયાથી બંધ છે",
        "અમારા વિસ્તારમાં ડેન્ગ્યુના ઘણા કેસ છે, કૃપા કરીને ફોગિંગ કરાવો",
        "સવારની બસ રોજ મોડી આવે છે",
        "દુકાનદારોએ આખી ફૂટપાથ પર કબજો કરી લીધો છે",
        "ગઈકાલે રાત્રે અમારા ઘરમાં ચોરી થઈ",
        "વાવાઝોડામાં મોટું ઝાડ રસ્તા પર પડી ગયું છે"], _CATS)),
    "Bengali": list(zip([
        "আমাদের এলাকায় তিন দিন ধরে জল আসছে না",
        "রাস্তায় বড় বড় গর্ত হয়েছে, গাড়ি চালানো কঠিন",
        "গতকাল রাত থেকে আমাদের এলাকায় বিদ্যুৎ নেই",
        "এক সপ্তাহ ধরে আবর্জনার গাড়ি আসেনি, ময়লার স্তূপ জমে গেছে",
        "নর্দমা উপচে পড়ছে এবং নোংরা জল বাড়িতে ঢুকছে",
        "আমাদের গলির রাস্তার আলো দুই সপ্তাহ ধরে বন্ধ",
        "আমাদের এলাকায় ডেঙ্গুর অনেক রোগী আছে, দয়া করে মশার ওষুধ স্প্রে করুন",
        "সকালের বাস রোজ দেরিতে আসে",
        "দোকানদাররা পুরো ফুটপাত দখল করে নিয়েছে",
        "গতকাল রাতে আমাদের বাড়িতে চুরি হয়েছে",
        "ঝড়ে একটি বড় গাছ রাস্তায় পড়ে গেছে"], _CATS)),
    "Tamil": list(zip([
        "எங்கள் பகுதியில் மூன்று நாட்களாக தண்ணீர் வரவில்லை",
        "சாலையில் பெரிய பள்ளங்கள் உள்ளன, வாகனம் ஓட்டுவது கடினம்",
        "நேற்று இரவு முதல் எங்கள் பகுதியில் மின்சாரம் இல்லை",
        "ஒரு வாரமாக குப்பை வண்டி வரவில்லை, குப்பை குவிந்துள்ளது",
        "சாக்கடை நிரம்பி வழிகிறது, கழிவுநீர் வீட்டிற்குள் வருகிறது",
        "எங்கள் தெருவில் தெரு விளக்குகள் இரண்டு வாரங்களாக எரியவில்லை",
        "எங்கள் பகுதியில் பலருக்கு டெங்கு காய்ச்சல் உள்ளது, கொசு மருந்து அடிக்கவும்",
        "காலை பேருந்து தினமும் தாமதமாக வருகிறது",
        "கடைக்காரர்கள் நடைபாதை முழுவதையும் ஆக்கிரமித்துள்ளனர்",
        "நேற்று இரவு எங்கள் வீட்டில் திருட்டு நடந்தது",
        "புயலில் ஒரு பெரிய மரம் சாலையில் விழுந்துவிட்டது"], _CATS)),
}
